export const regionNames = {
  "01": "Tarapacá",
  "02": "Antofagasta",
  "03": "Atacama",
  "04": "Coquimbo",
  "05": "Valparaíso",
  "06": "Libertador Gral. Bernardo O'Higgins",
  "07": "Maule",
  "08": "Biobío",
  "09": "Araucanía",
  "10": "Los Lagos",
  "11": "Aysén del General Carlos Ibáñez del Campo",
  "12": "Magallanes y de la Antártica Chilena",
  "13": "Metropolitana de Santiago",
  "14": "Los Ríos",
  "15": "Arica y Parinacota",
  "16": "Ñuble",
};
